/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartManagerCard: typeof import('./components/ChartManagerCard.vue')['default']
    ClockManagerCard: typeof import('./components/ClockManagerCard.vue')['default']
    LoginPopup: typeof import('./components/LoginPopup.vue')['default']
    NewsletterPopup: typeof import('./components/NewsletterPopup.vue')['default']
    ProfileDialog: typeof import('./components/ProfileDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamCard: typeof import('./components/TeamCard.vue')['default']
    TeamChartManagerCard: typeof import('./components/TeamChartManagerCard.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
    WorkingTimeCard: typeof import('./components/WorkingTimeCard.vue')['default']
    WorkingTimesCard: typeof import('./components/WorkingTimesCard.vue')['default']
  }
}
